<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Description>HttpAgent 是一个高性能、灵活且易用的开源库，提供了全面的 HTTP 功能支持，包括文件传输、轮询、测试工具、实时通信、请求管理、Media 类型处理、MessagePack 支持、声明式请求等。 内置工业级报文透视引擎（Profiler），彻底终结第三方 API 对接的“黑匣子”时代，并具有低资源消耗和高测试覆盖率的特点。</Description>
        <PackageTags>Furion;ASP.NET;dotNET China;Cross Platform;百小僧;Monk;MonkSoul;Core;HttpClient;Remote</PackageTags>
    </PropertyGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\HttpAgent\src\HttpAgent.csproj"/>
    </ItemGroup>

</Project>